on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "Deploying to production on Render..."
          curl -X POST ${{ secrets.RENDER_PROD_HOOK }}
